//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matna.Resources.Localize {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_ko_KR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ko_KR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Matna.AppResources.ko-KR", typeof(AppResources_ko_KR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Matna {
            get {
                return ResourceManager.GetString("Matna", resourceCulture);
            }
        }
        
        public static string Locale {
            get {
                return ResourceManager.GetString("Locale", resourceCulture);
            }
        }
        
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        public static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        public static string SearchForPlaces {
            get {
                return ResourceManager.GetString("SearchForPlaces", resourceCulture);
            }
        }
        
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string NetworkUnavailable {
            get {
                return ResourceManager.GetString("NetworkUnavailable", resourceCulture);
            }
        }
        
        public static string LoadPlacesFromMap {
            get {
                return ResourceManager.GetString("LoadPlacesFromMap", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string SavedPlaces {
            get {
                return ResourceManager.GetString("SavedPlaces", resourceCulture);
            }
        }
        
        public static string MoveMapPlease {
            get {
                return ResourceManager.GetString("MoveMapPlease", resourceCulture);
            }
        }
        
        public static string MaxRadReached {
            get {
                return ResourceManager.GetString("MaxRadReached", resourceCulture);
            }
        }
        
        public static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        public static string NoInfo {
            get {
                return ResourceManager.GetString("NoInfo", resourceCulture);
            }
        }
        
        public static string FindRoute {
            get {
                return ResourceManager.GetString("FindRoute", resourceCulture);
            }
        }
        
        public static string FindDetail {
            get {
                return ResourceManager.GetString("FindDetail", resourceCulture);
            }
        }
        
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        public static string SearchRadiusExplanation {
            get {
                return ResourceManager.GetString("SearchRadiusExplanation", resourceCulture);
            }
        }
        
        public static string ReallyQuit {
            get {
                return ResourceManager.GetString("ReallyQuit", resourceCulture);
            }
        }
        
        public static string KRQuickFilters {
            get {
                return ResourceManager.GetString("KRQuickFilters", resourceCulture);
            }
        }
        
        public static string KRQuickFiltersDetail {
            get {
                return ResourceManager.GetString("KRQuickFiltersDetail", resourceCulture);
            }
        }
        
        public static string Samdae {
            get {
                return ResourceManager.GetString("Samdae", resourceCulture);
            }
        }
        
        public static string Suyo {
            get {
                return ResourceManager.GetString("Suyo", resourceCulture);
            }
        }
        
        public static string Chakhan {
            get {
                return ResourceManager.GetString("Chakhan", resourceCulture);
            }
        }
        
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        public static string GoogleApi {
            get {
                return ResourceManager.GetString("GoogleApi", resourceCulture);
            }
        }
        
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        public static string MaxSearchRadius {
            get {
                return ResourceManager.GetString("MaxSearchRadius", resourceCulture);
            }
        }
        
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        public static string KeywordsDetail {
            get {
                return ResourceManager.GetString("KeywordsDetail", resourceCulture);
            }
        }
        
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        public static string GoogleAPIError {
            get {
                return ResourceManager.GetString("GoogleAPIError", resourceCulture);
            }
        }
        
        public static string SelectSort {
            get {
                return ResourceManager.GetString("SelectSort", resourceCulture);
            }
        }
        
        public static string SearchResultPage {
            get {
                return ResourceManager.GetString("SearchResultPage", resourceCulture);
            }
        }
        
        public static string SearchResultPageDetail {
            get {
                return ResourceManager.GetString("SearchResultPageDetail", resourceCulture);
            }
        }
    }
}
